language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.1
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      mono: latest
      dotnet: 1.0.1
  allow_failures:
    - os: osx

script:
  - ./build.sh GenerateDocs